import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import NavBar from "./_components/NavBar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    //winter or night
    <html lang="en" data-theme="winter">
      <body className={`font-sans ${inter.variable} flex h-screen flex-col `}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <NavBar />
          <div className="flex flex-1 bg-gradient-to-b from-[#2e026d] to-[#15162c] ">
            {children}
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
